# SVM

In [101]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [102]:
data = pd.read_csv('D1.csv')

In [103]:
data

humidity  precipMM  tempC  HeatStroke
0             72       0.0     18           0
1             72       0.0     19           0
2             72       0.0     18           0
3             72       0.0     18           0
4             68       0.0     20           0
...          ...       ...    ...         ...
116131        28       0.0     30           1
116132        29       0.0     29           0
116133        30       0.0     27           0
116134        31       0.0     26           0
116135        32       0.0     25           0

[116136 rows x 4 columns]

In [104]:

data.describe()

humidity       precipMM          tempC     HeatStroke
count  116136.000000  116136.000000  116136.000000  116136.000000
mean       57.646001       0.231727      25.304720       0.112489
std        25.316012       0.802657       4.659629       0.315968
min         4.000000       0.000000      11.000000       0.000000
25%        36.000000       0.000000      22.000000       0.000000
50%        58.000000       0.000000      24.000000       0.000000
75%        82.000000       0.100000      28.000000       0.000000
max       100.000000      25.700000      43.000000       1.000000

In [105]:
data = data.head(100000)
data.groupby('HeatStroke').mean()

humidity  precipMM      tempC
HeatStroke                                
0           62.268978   0.25337  24.202384
1           19.278506   0.00986  34.138696

In [106]:

# separating the data and labels
X = data.drop(columns = 'HeatStroke', axis=1)
Y = data['HeatStroke']


In [107]:
print(X,Y)

       humidity  precipMM  tempC
0            72       0.0     18
1            72       0.0     19
2            72       0.0     18
3            72       0.0     18
4            68       0.0     20
...         ...       ...    ...
99995        18       0.0     36
99996        14       0.0     38
99997        15       0.0     38
99998        16       0.0     38
99999        18       0.0     39

[100000 rows x 3 columns] 0        0
1        0
2        0
3        0
4        0
        ..
99995    1
99996    1
99997    1
99998    1
99999    1
Name: HeatStroke, Length: 100000, dtype: int64


In [108]:

scaler = StandardScaler()

In [109]:

scaler.fit(X)


StandardScaler()

In [110]:

standardized_data = scaler.transform(X)

In [111]:
print(standardized_data)

[[ 0.57886436 -0.29172471 -1.55770795]
 [ 0.57886436 -0.29172471 -1.34612753]
 [ 0.57886436 -0.29172471 -1.55770795]
 ...
 [-1.65820917 -0.29172471  2.67390046]
 [-1.61896226 -0.29172471  2.67390046]
 [-1.54046845 -0.29172471  2.88548088]]


In [112]:

X = standardized_data
Y = data['HeatStroke']

In [113]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [114]:

print(X.shape, X_train.shape, X_test.shape)

(100000, 3) (80000, 3) (20000, 3)


In [115]:

classifier = svm.SVC(kernel='linear')

In [116]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)


SVC(kernel='linear')

In [117]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [118]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.9771875


In [119]:

# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [120]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9778
